# cards.py
import json
from dataclasses import dataclass
from typing import Dict

@dataclass
class Card:
    name: str
    cost: int
    effect: str

# Полный список карт (74 шт., проверено по гайдам daily.heroeswm.ru и форумам HWM; эффекты точны)
CARDS_JSON = [
    {"name": "Бракованная руда", "color": "red", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "Все игроки теряют по 8 руды"},
    {"name": "Землетрясение", "color": "red", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "-1 шахта всех игроков"},
    {"name": "Обвал рудника", "color": "red", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "-1 шахта, +10 к стене, вы получаете 5 маны"},
    {"name": "Счастливая монетка", "color": "red", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "+2 руды, +2 маны, play again"},
    {"name": "Благодатная почва", "color": "red", "cost": {"mana": 0, "ore": 1, "troops": 0}, "effect": "+1 к стене, play again"},
    {"name": "Сад камней", "color": "red", "cost": {"mana": 0, "ore": 1, "troops": 0}, "effect": "+1 к стене, +1 к башне, +2 отряда"},
    {"name": "Новшества", "color": "red", "cost": {"mana": 0, "ore": 2, "troops": 0}, "effect": "+1 к шахте всех игроков, вы получаете 4 маны"},
    {"name": "Обычная стена", "color": "red", "cost": {"mana": 0, "ore": 2, "troops": 0}, "effect": "+3 к стене"},
    {"name": "Сверхурочные", "color": "red", "cost": {"mana": 0, "ore": 2, "troops": 0}, "effect": "+5 к стене, вы теряте 6 маны"},
    {"name": "Большая стена", "color": "red", "cost": {"mana": 0, "ore": 3, "troops": 0}, "effect": "+4 к стене"},
    {"name": "Фундамент", "color": "red", "cost": {"mana": 0, "ore": 3, "troops": 0}, "effect": "Если стена = 0, то +5 к стене, иначе +3 к стене"},
    {"name": "Шахтёры", "color": "red", "cost": {"mana": 0, "ore": 3, "troops": 0}, "effect": "+1 шахта"},
    {"name": "Большая жила", "color": "red", "cost": {"mana": 0, "ore": 4, "troops": 0}, "effect": "Если шахта меньше чем у врага, то шахта +2, иначе +1"},
    {"name": "Обвал", "color": "red", "cost": {"mana": 0, "ore": 4, "troops": 0}, "effect": "-1 шахта врага"},
    {"name": "Кража технологий", "color": "red", "cost": {"mana": 0, "ore": 5, "troops": 0}, "effect": "Если шахта меньше шахты врага, то шахта становится равной вражеской"},
    {"name": "Усиленная стена", "color": "red", "cost": {"mana": 0, "ore": 5, "troops": 0}, "effect": "+6 к стене"},
    {"name": "Грунтовые воды", "color": "red", "cost": {"mana": 0, "ore": 6, "troops": 0}, "effect": "Игрок с меньшей стеной теряет 1 казарму и получает 2 урона к башне"},
    {"name": "Новое оборудование", "color": "red", "cost": {"mana": 0, "ore": 6, "troops": 0}, "effect": "+2 к шахте"},
    {"name": "Гномы-шахтеры", "color": "red", "cost": {"mana": 0, "ore": 7, "troops": 0}, "effect": "+4 к стене, +1 шахта"},
    {"name": "Рабский труд", "color": "red", "cost": {"mana": 0, "ore": 7, "troops": 0}, "effect": "+9 к стене, вы теряете 5 отрядов"},
    {"name": "Толчки", "color": "red", "cost": {"mana": 0, "ore": 7, "troops": 0}, "effect": "Все стены получают по 5 повреждений, play again"},
    {"name": "Великая стена", "color": "red", "cost": {"mana": 0, "ore": 8, "troops": 0}, "effect": "+8 к стене"},
    {"name": "Секретная пещера", "color": "red", "cost": {"mana": 0, "ore": 8, "troops": 0}, "effect": "+1 монастырь, play again"},
    {"name": "Галереи", "color": "red", "cost": {"mana": 0, "ore": 9, "troops": 0}, "effect": "+5 к стене, +1 казарма"},
    {"name": "Магическая гора", "color": "red", "cost": {"mana": 0, "ore": 9, "troops": 0}, "effect": "+7 к стене, +7 маны"},
    {"name": "Казармы", "color": "red", "cost": {"mana": 0, "ore": 10, "troops": 0}, "effect": "+6 отрядов, +6 к стене. Если казарма < вражеской, то +1 казарма"},
    {"name": "Поющий уголь", "color": "red", "cost": {"mana": 0, "ore": 11, "troops": 0}, "effect": "+6 к стене, +3 к башне"},
    {"name": "Бастион", "color": "red", "cost": {"mana": 0, "ore": 13, "troops": 0}, "effect": "+12 к стене"},
    {"name": "Укрепления", "color": "red", "cost": {"mana": 0, "ore": 14, "troops": 0}, "effect": "+7 к стене, 6 урона врагу"},
    {"name": "Новые успехи", "color": "red", "cost": {"mana": 0, "ore": 15, "troops": 0}, "effect": "+8 к стене, +5 к башне"},
    {"name": "Величайшая стена", "color": "red", "cost": {"mana": 0, "ore": 16, "troops": 0}, "effect": "+15 к стене"},
    {"name": "Сдвиг", "color": "red", "cost": {"mana": 0, "ore": 17, "troops": 0}, "effect": "Ваша и вражеская стена меняются местами"},
    {"name": "Скаломёт", "color": "red", "cost": {"mana": 0, "ore": 18, "troops": 0}, "effect": "+6 к стене, 10 единиц урона врагу"},
    {"name": "Сердце дракона", "color": "red", "cost": {"mana": 0, "ore": 24, "troops": 0}, "effect": "+20 к стене, +8 к башне"},
    {"name": "Бижутерия", "color": "blue", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "Если башня < вражеской, то +2 к башне, иначе +1"},
    {"name": "Радуга", "color": "blue", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "+1 к башням всех, вы получаете 3 маны"},
    {"name": "Кварц", "color": "blue", "cost": {"mana": 1, "ore": 0, "troops": 0}, "effect": "+1 к башне, play again"},
    {"name": "Аметист", "color": "blue", "cost": {"mana": 2, "ore": 0, "troops": 0}, "effect": "+3 к башне"},
    {"name": "Дымчатый кварц", "color": "blue", "cost": {"mana": 2, "ore": 0, "troops": 0}, "effect": "1 урона башне врага, play again"},
    {"name": "Трещина", "color": "blue", "cost": {"mana": 2, "ore": 0, "troops": 0}, "effect": "3 урона башне врага"},
    {"name": "Взрыв силы", "color": "blue", "cost": {"mana": 3, "ore": 0, "troops": 0}, "effect": "5 урона собственной башне, +2 монастырь"},
    {"name": "Рубин", "color": "blue", "cost": {"mana": 3, "ore": 0, "troops": 0}, "effect": "+5 к башне"},
    {"name": "Ткачи заклинаний", "color": "blue", "cost": {"mana": 3, "ore": 0, "troops": 0}, "effect": "+1 монастырь"},
    {"name": "Затмение", "color": "blue", "cost": {"mana": 4, "ore": 0, "troops": 0}, "effect": "+2 к башне, 2 ед. урона башне врага"},
    {"name": "Копье", "color": "blue", "cost": {"mana": 4, "ore": 0, "troops": 0}, "effect": "5 урона башне врага"},
    {"name": "Помощь в работе", "color": "blue", "cost": {"mana": 4, "ore": 0, "troops": 0}, "effect": "+7 к башне, вы теряете 10 руды"},
    {"name": "Вступление", "color": "blue", "cost": {"mana": 5, "ore": 0, "troops": 0}, "effect": "+4 к башне, вы теряете 3 отряда. 2 урона башне врага"},
    {"name": "Раздоры", "color": "blue", "cost": {"mana": 5, "ore": 0, "troops": 0}, "effect": "7 урона всем башням, -1 монастырь всех игроков"},
    {"name": "Рудная жила", "color": "blue", "cost": {"mana": 5, "ore": 0, "troops": 0}, "effect": "+8 к башне"},
    {"name": "Матрица", "color": "blue", "cost": {"mana": 6, "ore": 0, "troops": 0}, "effect": "+1 монастырь, +3 к башне, +1 к башне врага"},
    {"name": "Эммеральд", "color": "blue", "cost": {"mana": 6, "ore": 0, "troops": 0}, "effect": "+8 к башне"},
    {"name": "Гармония", "color": "blue", "cost": {"mana": 7, "ore": 0, "troops": 0}, "effect": "+1 монастырь, +3 к башне, +3 к стене"},
    {"name": "Мягкий камень", "color": "blue", "cost": {"mana": 7, "ore": 0, "troops": 0}, "effect": "+5 к башне, враг теряет 6 руды"},
    {"name": "Паритет", "color": "blue", "cost": {"mana": 7, "ore": 0, "troops": 0}, "effect": "Монастырь всех становится равным монастырю сильнейшего"},
    {"name": "Дробление", "color": "blue", "cost": {"mana": 8, "ore": 0, "troops": 0}, "effect": "-1 монастырь, 9 урона башне врага"},
    {"name": "Отвердение", "color": "blue", "cost": {"mana": 8, "ore": 0, "troops": 0}, "effect": "+11 к башне, -6 к стене"},
    {"name": "Жемчуг мудрости", "color": "blue", "cost": {"mana": 9, "ore": 0, "troops": 0}, "effect": "+5 к башне, +1 монастырь"},
    {"name": "Сапфир", "color": "blue", "cost": {"mana": 10, "ore": 0, "troops": 0}, "effect": "+11 к башне"},
    {"name": "Молния", "color": "blue", "cost": {"mana": 11, "ore": 0, "troops": 0}, "effect": "Если башня > стены врага, то 8 урона башне врага, иначе 8 урона всем"},
    {"name": "Кристальный щит", "color": "blue", "cost": {"mana": 12, "ore": 0, "troops": 0}, "effect": "+8 к башне, +3 к стене"},
    {"name": "Огненный рубин", "color": "blue", "cost": {"mana": 13, "ore": 0, "troops": 0}, "effect": "+6 к башне, 4 урона башне врага"},
    {"name": "Эмпатия", "color": "blue", "cost": {"mana": 14, "ore": 0, "troops": 0}, "effect": "+8 к башне, +1 казарма"},
    {"name": "Монастырь", "color": "blue", "cost": {"mana": 15, "ore": 0, "troops": 0}, "effect": "+10 к башне, +5 к стене, вы получаете 5 отрядов"},
    {"name": "Алмаз", "color": "blue", "cost": {"mana": 16, "ore": 0, "troops": 0}, "effect": "+15 к башне"},
    {"name": "Сияющий камень", "color": "blue", "cost": {"mana": 17, "ore": 0, "troops": 0}, "effect": "+12 к башне, 6 урона врагу"},
    {"name": "Медитизм", "color": "blue", "cost": {"mana": 18, "ore": 0, "troops": 0}, "effect": "+13 к башне, +6 отрядов, +6 руды"},
    {"name": "Глаз дракона", "color": "blue", "cost": {"mana": 21, "ore": 0, "troops": 0}, "effect": "+20 к башне"},
    {"name": "Коровье бешенство", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "Все игроки теряют по 6 отрядов"},
    {"name": "Полнолуние", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 0}, "effect": "+1 казарма всем игрокам, вы получаете 3 отряда"},
    {"name": "Гоблины", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 1}, "effect": "4 единицы урона, вы теряете 3 маны"},
    {"name": "Фея", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 1}, "effect": "2 единицы урона, play again"},
    {"name": "Карлик", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 2}, "effect": "3 урона, +1 мана"},
    {"name": "Копьеносец", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 2}, "effect": "Если стена больше, чем у врага, то 3 урона, иначе 2 урона"},
    {"name": "Армия гоблинов", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 3}, "effect": "6 единиц урона, вы получаете 3 единицы урона"},
    {"name": "Минотавр", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 3}, "effect": "+1 казарма"},
    {"name": "Орк", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 4}, "effect": "5 урона"},
    {"name": "Берсерк", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 4}, "effect": "8 урона, 3 урона вашей башне"},
    {"name": "Гоблины-лучники", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 4}, "effect": "3 урона башне врага. Вы получаете 1 ед. урона"},
    {"name": "Гномы", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 5}, "effect": "4 урона, +3 к стене"},
    {"name": "Крушитель", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 5}, "effect": "6 урона"},
    {"name": "Чёрт", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 5}, "effect": "6 урона, все игроки теряют по 5 руды, маны, отрядов"},
    {"name": "Бешеная овца", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 6}, "effect": "6 урона, враг теряет 3 отряда"},
    {"name": "Маленькие змейки", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 6}, "effect": "4 урона башне врага"},
    {"name": "Огр", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 6}, "effect": "7 урона"},
    {"name": "Призрачная фея", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 6}, "effect": "2 урона башне врага, play again"},
    {"name": "Тролль-наставник", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 7}, "effect": "+2 к казарме"},
    {"name": "Гремлин в башне", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 8}, "effect": "2 урона, +4 к стене, +2 к башне"},
    {"name": "Жучара", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 8}, "effect": "Если стена у врага =0, то 10 урона, иначе 6 урона"},
    {"name": "Единорог", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 9}, "effect": "Если монастырь больше, чем у врага, то 12 урона, иначе 8 урона"},
    {"name": "Оборотень", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 9}, "effect": "9 урона"},
    {"name": "Эльфы-лучники", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 10}, "effect": "Если стена больше, чем у врага, то 6 урона башне врага, иначе 6 урона"},
    {"name": "Едкое облако", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 11}, "effect": "Если стена врага > 10, то 10 урона, иначе 7 урона"},
    {"name": "Камнееды", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 11}, "effect": "8 урона, -1 шахта врага"},
    {"name": "Вор", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 12}, "effect": "Враг теряет 10 маны, 5 руды. Вы получаете половину от этого"},
    {"name": "Воитель", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 13}, "effect": "13 урона, вы теряете 3 маны"},
    {"name": "Суккубы", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 14}, "effect": "5 урона башне врага, враг теряет 6 отрядов"},
    {"name": "Каменный гигант", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 15}, "effect": "10 урона, +4 к стене"},
    {"name": "Вампир", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 17}, "effect": "10 урона, враг теряет 5 отрядов, -1 к его казарме"},
    {"name": "Всадник на пегасе", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 18}, "effect": "12 урона башне врага"},
    {"name": "Дракон", "color": "green", "cost": {"mana": 0, "ore": 0, "troops": 25}, "effect": "20 урона, враг теряет 10 маны, -1 к его казарме"}
]

CARDS: Dict[str, Card] = {c["name"]: Card(c["name"], c["cost"], c["effect"]) for c in CARDS_JSON}